import dns from "node:dns";
dns.setServers(['8.8.8.8','8.8.4.4']);

import { Outfit} from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { ToastContainer } from "react-toastify";

const outfit = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        <main>
        {children}
        </main>
        <Footer/>
        <ToastContainer/>
        </body>
    </html>
  );
}
